# Generated by Django 3.0.8 on 2020-07-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('real_name', models.CharField(max_length=100)),
                ('tz', models.CharField(max_length=100)),
                ('activity_periods', models.TimeField()),
                ('start_time', models.DateTimeField()),
                ('End_time', models.DateTimeField()),
            ],
        ),
    ]
